### PR TITLE
Make sure that WAL-file doesn't blow up in size

### PR DESCRIPTION
**Pull request by stigger**
Before:
```
$ ls -lah ChatSecure-media.sqlite*
-rw-r--r--@ 1 stigger  access_bpf    10M Sep 19 14:59 ChatSecure-media.sqlite
-rw-r--r--@ 1 stigger  access_bpf    32K Sep 19 15:06 ChatSecure-media.sqlite-shm
-rw-r--r--@ 1 stigger  access_bpf   527M Sep 19 14:59 ChatSecure-media.sqlite-wal
```
After:
```
$ ls -lah ChatSecure-media.sqlite*
-rw-r--r--@ 1 stigger  access_bpf    15M Sep 19 22:13 ChatSecure-media.sqlite
-rw-r--r--@ 1 stigger  access_bpf    32K Sep 19 22:14 ChatSecure-media.sqlite-shm
-rw-r--r--@ 1 stigger  access_bpf     0B Sep 19 22:14 ChatSecure-media.sqlite-wal
```

### CODE REVIEW

**Review by chrisballinger — COMMENTED** [review]
Nice! I think that the reason the WAL file grows in size forever is because of an issue of how we are mishandling YapDatabase connections in some way that I've never been able to track down. I think the CI failure is resolvable just by removing the `exclusive => true` from the test Podfiles because that option no longer exists in newer version of CocoaPods. Good to merge once CI is passing.

**Comment by stigger** [comment]
Well, in my particular case the problem was with the media database, so the lifecycles of the YapDatabase connections should affect this.

**Comment by chrisballinger** [comment]
Ah ya good call. I guess Travis CI changed their Xcode images because it's still failing on: `xctool -workspace Example/IOCipher.xcworkspace -scheme IOCipherTests -sdk iphonesimulator -arch i386 test`. Could also be worth bumping the Travis Xcode image to something more recent.

We could probably change that `xctool` line to `xcodebuild -workspace Example/IOCipher.xcworkspace -scheme IOCipherTests -sdk iphonesimulator -arch x86_64 -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' test | xcpretty -c`

**Comment by stigger** [comment]
It took a while, but I finally managed to resurrect the tests.

**Review by chrisballinger — APPROVED** [review]
Awesome! Thank you for sorting that out.

**Pull request merged**
